// PROBLEM 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

// Generates a Fibonacci Sequence array of size n
function generateFibWithRestriction(n: number): number[]
{
    let fibList: number[] = [1, 2];
    for (let i = 2; i < n; i++)
    {
        fibList[i] = fibList[i-1] + fibList[i-2];
    }

    return fibList;
}

let sumFib: number = 0;
let fibList: number[] = generateFibWithRestriction(50 /*size of array*/);

fibList.forEach((value: number) => {
    if (value % 2 === 0 && value < 4000000)
    {
        sumFib += value;
    }
})

console.log(sumFib);
